import fs from "node:fs/promises";
import path from "node:path";
import { loadAndValidateSchemas } from "../lib/load-schemas.js";
import { generatedDir } from "../lib/paths.js";
import type {
  EventSchema,
  LogSchema,
  ObservabilitySchema,
  PropertyDef,
  ValidationIssue,
} from "../lib/schema-model.js";

function toPascalCase(name: string): string {
  return name
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function propertyTypeToTs(def: PropertyDef): string {
  switch (def.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "object":
      return "Record<string, unknown>";
    case "array":
      return "unknown[]";
    default:
      return "unknown";
  }
}

function renderPropsInterface(
  interfaceName: string,
  props: Record<string, PropertyDef> | undefined,
): string {
  const entries = Object.entries(props ?? {});
  if (entries.length === 0) {
    return `export type ${interfaceName} = Record<string, never>;`;
  }

  const lines = entries.map(([key, def]) => {
    const comment = def.description
      ? `  /** ${def.description.replace(/\*\//g, "*\\/")} */\n`
      : "";
    return `${comment}  ${JSON.stringify(key)}: ${propertyTypeToTs(def)};`;
  });

  return `export interface ${interfaceName} {\n${lines.join("\n")}\n}`;
}

function renderTypes(schemas: ObservabilitySchema[]): string {
  const chunks: string[] = [
    "/* eslint-disable */",
    "// Generated by @client-platform/observability — do not edit by hand.",
    "",
    'export type LogLevel = "debug" | "info" | "warn" | "error";',
    "",
  ];

  const eventProps: string[] = [];
  const logFields: string[] = [];

  for (const schema of schemas) {
    if (schema.kind === "event") {
      const propsName = `${toPascalCase(schema.name)}Properties`;
      chunks.push(renderPropsInterface(propsName, schema.properties));
      chunks.push("");
      eventProps.push(`  ${JSON.stringify(schema.name)}: ${propsName};`);
    } else {
      const fieldsName = `${toPascalCase(schema.name)}Fields`;
      chunks.push(renderPropsInterface(fieldsName, schema.fields));
      chunks.push("");
      logFields.push(`  ${JSON.stringify(schema.name)}: ${fieldsName};`);
    }
  }

  chunks.push("export interface EventPropertiesMap {");
  chunks.push(eventProps.length ? eventProps.join("\n") : "  // no events");
  chunks.push("}");
  chunks.push("");
  chunks.push("export type EventName = keyof EventPropertiesMap;");
  chunks.push("");
  chunks.push("export interface LogFieldsMap {");
  chunks.push(logFields.length ? logFields.join("\n") : "  // no logs");
  chunks.push("}");
  chunks.push("");
  chunks.push("export type LogName = keyof LogFieldsMap;");
  chunks.push("");

  return `${chunks.join("\n")}\n`;
}

function renderConstants(schemas: ObservabilitySchema[]): string {
  const events = schemas.filter((s): s is EventSchema => s.kind === "event");
  const logs = schemas.filter((s): s is LogSchema => s.kind === "log");

  const eventNames = events.map((e) => `  ${JSON.stringify(e.name)},`).join("\n");
  const logNames = logs.map((l) => `  ${JSON.stringify(l.name)},`).join("\n");

  const levelBlocks = logs
    .map((log) => {
      const levels = log.levels.map((l) => `    ${JSON.stringify(l)},`).join("\n");
      return `  ${JSON.stringify(log.name)}: [\n${levels}\n  ] as const,`;
    })
    .join("\n");

  return `/* eslint-disable */
// Generated by @client-platform/observability — do not edit by hand.

export const EVENT_NAMES = [
${eventNames || "  // none"}
] as const;

export const LOG_NAMES = [
${logNames || "  // none"}
] as const;

export const LOG_LEVELS = ["debug", "info", "warn", "error"] as const;

export const LOG_LEVELS_BY_NAME = {
${levelBlocks || "  // none"}
} as const;
`;
}

function renderHelpers(): string {
  return `/* eslint-disable */
// Generated by @client-platform/observability — do not edit by hand.
import type { EventName, EventPropertiesMap, LogFieldsMap, LogLevel, LogName } from "./types.js";
import { LOG_LEVELS_BY_NAME } from "./constants.js";

export type TrackPayload<N extends EventName> = {
  name: N;
  properties: EventPropertiesMap[N];
  timestamp?: string;
};

export type LogPayload<N extends LogName> = {
  name: N;
  level: LogLevel;
  fields?: LogFieldsMap[N];
  timestamp?: string;
};

export type ObservabilitySink = {
  track: (payload: TrackPayload<EventName>) => void;
  log: (payload: LogPayload<LogName>) => void;
};

const defaultSink: ObservabilitySink = {
  track(payload) {
    console.info("[observability:track]", payload);
  },
  log(payload) {
    console.info("[observability:log]", payload);
  },
};

let sink: ObservabilitySink = defaultSink;

/** Replace the default console sink (e.g. with a transport adapter). */
export function setObservabilitySink(next: ObservabilitySink): void {
  sink = next;
}

/** Typed event helper generated from observability/schemas/event.*.json */
export function track<N extends EventName>(
  name: N,
  properties: EventPropertiesMap[N],
): void {
  sink.track({
    name,
    properties,
    timestamp: new Date().toISOString(),
  });
}

/** Typed log helper generated from observability/schemas/log.*.json */
export function log<N extends LogName>(
  name: N,
  level: LogLevel,
  fields?: LogFieldsMap[N],
): void {
  const allowed = LOG_LEVELS_BY_NAME[name] as readonly LogLevel[] | undefined;
  if (allowed && !allowed.includes(level)) {
    throw new Error(\`level "\${level}" is not allowed for log "\${String(name)}"\`);
  }
  sink.log({
    name,
    level,
    fields,
    timestamp: new Date().toISOString(),
  });
}
`;
}

function renderIndex(): string {
  return `/* eslint-disable */
// Generated by @client-platform/observability — do not edit by hand.
export * from "./types.js";
export * from "./constants.js";
export * from "./helpers.js";
`;
}

function printIssues(issues: ValidationIssue[]): void {
  for (const issue of issues) {
    const pointer = issue.pointer ? ` ${issue.pointer}` : "";
    console.error(`  ✗ ${issue.file}${pointer}: ${issue.message}`);
  }
}

export type GenerateOptions = {
  cwd?: string;
};

export async function generateCommand(
  options: GenerateOptions = {},
): Promise<number> {
  const cwd = options.cwd ?? process.cwd();
  const { schemas, issues } = await loadAndValidateSchemas(cwd);

  if (issues.length > 0) {
    console.error(
      `[observability] generate aborted — fix validation issues first (${issues.length})`,
    );
    printIssues(issues);
    return 1;
  }

  const outDir = generatedDir(cwd);
  await fs.mkdir(outDir, { recursive: true });

  const models = schemas.map((s) => s.schema);
  const files: Array<[string, string]> = [
    ["types.ts", renderTypes(models)],
    ["constants.ts", renderConstants(models)],
    ["helpers.ts", renderHelpers()],
    ["index.ts", renderIndex()],
  ];

  for (const [name, contents] of files) {
    await fs.writeFile(path.join(outDir, name), contents, "utf8");
  }

  console.log(
    `[observability] generate ok — wrote ${files.length} file(s) to ${path.relative(cwd, outDir)}`,
  );
  for (const [name] of files) {
    console.log(`  + ${path.join(path.relative(cwd, outDir), name)}`);
  }
  return 0;
}
